version: "3.9"
services:
  postgres-it:
    image: "postgres:14.2"
    container_name: "tam-pg-it"
    hostname: postgres-service
    network_mode: bridge
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=supersecret
      - POSTGRES_DB=application-db
    ports:
      - "25432:5432"
